<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-02-13T15:32:14+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Berlin',
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyCZSSZTXQzobIFuJheGQxliweur2Orr8H0',
        ],
    ],
];
