<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-03-14T13:51:48+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.3.1',
    'version_db_installed' => '20171218000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1516196255,
        'do_page_reindex_check' => false,
        'latest_version' => '8.3.1',
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
];
